### ISSUE TITLE
Chrome Webstore asks for "management" permissions

### ISSUE THREAD

**Issue by SnoFox** [Lordmau5/BTTV4FFZ#13]
Hey,

I've noticed that the version on the Chrome Webstore is requesting the ability to manage my apps, themes, and extensions.

This seems dangerous and not required for BTTV4FFZ, especially considering the version in GitHub no longer requests that. I've installed the unpacked version from GitHub for now, but would love to see the Chrome Webstore edition fixed so people have enhanced security and I can have auto-updates ;]

**Comment by Lordmau5** [comment]
Holy fuck, you're right!

Well, I mean `management` was the easiest to go by to get the cross-origin headers working (https://github.com/Lordmau5/BTTV4FFZ/blob/master/Chrome/chrome/requests.js).

However, I had the changed `manifest.json` in my dev-environment the whole time, just didn't pack and upload it to Chrome.

v1.1.1 is publishing right now and it should have the fixed permissions :)


Thank you for pointing this out! I'll keep the issue open so you can report if it's fixed (wouldn't hurt to know it from a 2nd person other than me who might get it earlier due to having Chrome linked with my account yadda yadda yadda ;) )

**Comment by Lordmau5** [comment]
Alright, v1.1.1 is up now and it doesn't require `management` anymore :)

Once again, thanks for the heads-up! :D

**Comment by SnoFox** [comment]
LGTM. :shipit: https://www.snofox.net/share/perm/github/bttv4ffz.png
