### ISSUE TITLE
Chrome extension doesn't exist, Firefox addon no longer works.

### ISSUE THREAD

**Issue by simoniz0r** [Lordmau5/BTTV4FFZ#17]
So, after doing some digging around, I've gathered that you're changing "BTTV4FFZ" to "FFZ Addon Pack," but you've done basically nothing to inform users who are currently using BTTV4FFZ of the change.  Furthermore, none of the extensions/addons that you have currently released seem to work.  The Chrome extension seems to not exist at all, and the Firefox addon seems to do nothing.  The script for the FFZ Addon Pack does work in Firefox, but there is no real alternative to Tampermonkey for Chrome.  Stylish is about as close as you get, and Stylish does not work with the script you have released.

For me, BTTV4FFZ is pretty much essential when using FFZ.  For now, I'm stuck in Firefox with the script (which I don't care for because FF performs poorly on my PC).  I'm sure there are people out there who have no idea what's going on and would like some answers...  I mean, your website says nothing of the change.  The Chrome store page for BTTV4FFZ is just an error now.  No redirect to the new extension, no explanation of what's going on, just nothing.  Your Twitter link no longer works; it redirects to a search page where I just happened to stumble upon your new Twitter account.

Please do your best to inform people of what's going on here.  If I hadn't stumbled on your Twitter page, I would have had no idea that you were transitioning to a new name.

**Comment by Lordmau5** [comment]
Okay, let's wrap everything together:

It isn't available on Chrome right now you are right. 
Is it my fault? No. 
The Chrome dev people decided to take it down because I'm doing remote script loading (which a lot of other extensions do as well). 
I'm in contact with them though in regards to this. 

As for Tampermonkey on Chrome - of course there it exists. I don't know where you looked but literally the first Google result for "Tampermonkey" shows me the link to the Chrome webstore:
https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo

The website is being redone and once I have it done, the old one will forward to it, don't worry. 

As for the Twitter handle, there's not much I could do. You sadly can't support old handles to work alongside new ones :/

**Comment by Lordmau5** [comment]
Chrome extension is back, Firefox support is also back in.

Please check the "Download" section on the new repo for both :)

https://github.com/Lordmau5/The-FFZ-Addon-Pack
