### ISSUE TITLE
user globally emotes don't show up

### ISSUE THREAD

**Issue by cineafx** [Lordmau5/BTTV4FFZ#3]
If somebody has a globally usable emote from the "BetterTTV Pro Subscription" it does not show up in the chat as the emote.

**Comment by Lordmau5** [comment]
I would need to hook into BTTV's socket server for that, which should not be *impossible*.

However, I don't have an active BTTV Pro Subscription (mainly due to the fact that I don't need, want or like the idea of it) and can therefore not test it.

I would need someone to actively test it with me, and I don't know anyone that could... :/
(Even if it means to just post emotes in someone's chat)

**Comment by cineafx** [comment]
I don't know anybody either. But at least I know that it isn't a problem on my side. If I find somebody with a Subscription I will try to help you.

**Comment by Lordmau5** [comment]
Alright, bringing this up:
It's added ;)

**Comment by cineafx** [comment]
Awesome!
